stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

sylius_product:
    classes:
        product:
            model: Sylius\Component\Product\Model\Product
            controller: Sylius\Bundle\ProductBundle\Controller\ProductController
            repository: Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductRepository

sylius_archetype:
    classes:
        product:
            subject: Sylius\Component\Product\Model\Product
            attribute: Sylius\Component\Product\Model\Attribute
            option: Sylius\Component\Product\Model\Option
            archetype:
                model: Sylius\Component\Product\Model\Archetype

sylius_attribute:
    classes:
        product:
            subject: Sylius\Component\Product\Model\Product
            attribute:
                model: Sylius\Component\Product\Model\Attribute
            attribute_value:
                model: Sylius\Component\Product\Model\AttributeValue

sylius_variation:
    classes:
        product:
            variable: Sylius\Component\Product\Model\Product
            variant:
                model: Sylius\Component\Product\Model\Variant
                repository: Sylius\Bundle\ProductBundle\Doctrine\ORM\VariantRepository

sylius_translation:
    default_locale: %locale%
